### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Accept111** [huai-chang/DiffEIC#2]
作者你好，我在论文中看到你使用的是LSDIR数据集，我进入到该数据集官网，发现有16个高分别率数据集和3个低分辨率集合，我应该下载哪个去复现你的论文，数据集又应该如何进行组织。
感谢作者回答！

**Comment by huai-chang** [comment]
官网中的16个文件共同组成了LSDIR数据集，共包含84,991张图片。所以这16个文件都需要下载。解压后所有图片大小之和约为145G。当然，你也可以选择使用部分图片进行训练。

**Comment by Accept111** [comment]
我看在论文中写的是在4090上训练的，我想问一下训练时间大概是多久。

**Comment by huai-chang** [comment]
我是用单卡4090训练，一个模型差不多需要2到3天吧。

**Comment by Accept111** [comment]
打扰作者了，我在跑训练的代码的时候遇到了一个错误，RuntimeError: The size of tensor a (87) must match the size of tensor b (88) at non-singleton dimension 3，请问作者这是怎么回事。

**Comment by huai-chang** [comment]
你这是在验证的时候出现的错误吧。因为在验证的时候是直接使用原图，没有对其尺度进行处理，所以你需要确保你的验证集图片的长和宽都是64的倍数。我是直接将Kodak数据集用于验证的，你也可以对代码进行修改，添加图像前处理操作，或者手动裁剪你的验证集图片。

**Comment by Accept111** [comment]
我确定是在训练的时候出的问题，这是完整的报错信息，麻烦作者帮忙看一下。
  | Name              | Type                   | Params
-------------------------------------------------------------
0 | model             | DiffusionWrapper       | 865 M 
1 | first_stage_model | AutoencoderKL          | 83.7 M
2 | cond_stage_model  | FrozenOpenCLIPEmbedder | 354 M 
3 | control_model     | CDDM                   | 24.4 M
4 | preprocess_model  | LFGCM                  | 51.5 M
-------------------------------------------------------------
941 M     Trainable params
437 M     Non-trainable params
1.4 B     Total params
5,518.003 Total estimated model params size (MB)
Validation sanity check: 0it [00:00, ?it/s]/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:110: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 40 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Validation sanity check:   0%|                                                                                                                                               | 0/2 [00:00<?, ?it/s]/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py:56: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    main()
  File "train.py", line 31, in main
    trainer.fit(model, datamodule=data_module)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in fit
    self._call_and_handle_interrupt(
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run
    self._dispatch()
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1272, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1282, in run_stage
    return self._run_train()
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1304, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1368, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 109, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 123, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 215, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 236, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 446, in validation_step
    return self.model(*args, **kwargs)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 92, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/raid/jzk/DiffEIC/model/diffeic.py", line 805, in validation_step
    log, bpp = self.log_images(batch, bs=None)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/raid/jzk/DiffEIC/model/diffeic.py", line 680, in log_images
    z, c = self.get_input(batch, self.first_stage_key, bs=bs)
  File "/raid/jzk/DiffEIC/model/diffeic.py", line 654, in get_input
    c_latent, likelihoods, q_likelihoods = self.apply_condition_encoder(control, x)
  File "/raid/jzk/DiffEIC/model/diffeic.py", line 624, in apply_condition_encoder
    c_latent, likelihoods, q_likelihoods = self.preprocess_model(control, x)
  File "/home/jzk/anaconda3/envs/diffeic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/raid/jzk/DiffEIC/model/lfgcm.py", line 335, in forward
    slice_anchor = quantize_ste(slice_anchor - means_anchor) + means_anchor
RuntimeError: The size of tensor a (87) must match the size of tensor b (88) at non-singleton dimension 3

**Comment by Accept111** [comment]
感谢作者

**Comment by Accept111** [comment]
作者，就是你的代码是跑多少个epoch呢

**Comment by huai-chang** [comment]
我是完全按照论文描述进行训练的：

'We first train the proposed DiffEIC with $\lambda=1$ for 300K iterations, and then adapt them using target $\lambda$ for another 200K iterations. '

如果使用LSDIR数据集进行训练的话，一个 epoch 差不多是 20K iterations。

**Comment by djp0246** [comment]
您好，我从数据集官方网站上面查看LSDIR数据集已经失效了，huggingface上面的数据集格式又不一致，目前遇到了困难。您是否还有数据集的文件，能否分享一下？非常感谢。

**Comment by Accept111** [comment]
> 您好，我从数据集官方网站上面查看LSDIR数据集已经失效了，huggingface上面的数据集格式又不一致，目前遇到了困难。您是否还有数据集的文件，能否分享一下？非常感谢。

能否加个联系方式，我最近也在做相关工作。

**Comment by djp0246** [comment]
刚刚看到，非常感谢您提供的数据集，通过百度网盘联系您了。再次表示感谢~也感谢作者提供的开源代码，对我有很大的帮助！

**Comment by djp0246** [comment]
我刚刚下载了数据集，不过数量上比论文里面的84991少，是不是还有一个shard-00.tar.gz文件呢？麻烦您看一下有没有相关的文件呢？谢谢

**Comment by paomian001** [comment]
@djp0246 @Accept111 @huai-chang 您好请问您还能发一下数据集吗

**Comment by paomian001** [comment]
@huai-chang 好的好的 非常感谢！ 另外，训练结束后，checkpoints文件夹并未将训练好的权重进行保存，这是为啥呢？

**Comment by huai-chang** [comment]
还是上传到百度网盘了，阿里云盘我这上传太慢了
链接: https://pan.baidu.com/s/1IvowtZSRAPn_CnhhASEqgw?pwd=nck8 提取码: nck8

**Comment by huai-chang** [comment]
> [@huai-chang](https://github.com/huai-chang) 好的好的 非常感谢！ 另外，训练结束后，checkpoints文件夹并未将训练好的权重进行保存，这是为啥呢？

你可以检查检查代码。按理来说，原始代码每5000步会自动保存模型到``./logs/example/lightning_logs/version_0/checkpoints``中

**Comment by paomian001** [comment]
好的！非常感谢
